apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-09-06T08:34:27Z"
  labels:
    app: restapi-deployment
  name: restapi-deployment
  namespace: restapi
  resourceVersion: "41562"
  uid: f20a6312-c3cc-4d44-b38f-4c2006e796e2
spec:
  clusterIP: 10.99.3.194
  clusterIPs:
  - 10.99.3.194
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: restapi-deployment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
